#!/usr/bin/env python
"""
Train YOLOv8 Police Car Detection Model

This script trains a YOLOv8 medium model on the Chicago police cars dataset
with the annotations generated by auto_annotate.py.

The dataset structure should be:
  police_cars_dataset/
    images/
      train/  (92 images)
      val/    (11 images)
      test/   (12 images)
    labels/
      train/  (92 .txt files)
      val/    (11 .txt files)
      test/   (12 .txt files)
    data.yaml

Run:
    python train_now.py
"""

from ultralytics import YOLO
from pathlib import Path
import yaml
import sys

def main():
    print("\n" + "=" * 70)
    print("YOLO MODEL TRAINING - Chicago Police Cars Detection")
    print("=" * 70)
    
    # Check dataset exists
    dataset_dir = Path("police_cars_dataset")
    data_yaml = dataset_dir / "data.yaml"
    
    if not data_yaml.exists():
        print(f"Error: data.yaml not found at {data_yaml}")
        return False
    
    print(f"\nDataset config: {data_yaml}")
    
    # Read and display dataset info
    with open(data_yaml, 'r') as f:
        dataset_config = yaml.safe_load(f)
    
    print(f"Classes: {dataset_config.get('names', [])}")
    print(f"Train path: {dataset_config.get('train')}")
    print(f"Val path: {dataset_config.get('val')}")
    print(f"Test path: {dataset_config.get('test')}")
    
    # Verify label files exist
    labels_dir = dataset_dir / "labels"
    train_labels = list((labels_dir / "train").glob("*.txt"))
    val_labels = list((labels_dir / "val").glob("*.txt"))
    test_labels = list((labels_dir / "test").glob("*.txt"))
    
    print(f"\nLabel files:")
    print(f"  Train: {len(train_labels)} files")
    print(f"  Val: {len(val_labels)} files")
    print(f"  Test: {len(test_labels)} files")
    
    if len(train_labels) == 0:
        print("\nError: No training labels found!")
        print("Run auto_annotate.py first to generate annotations.")
        return False
    
    print("\n" + "=" * 70)
    print("STARTING TRAINING")
    print("=" * 70)
    print("\nTraining configuration:")
    print("  Model: YOLOv8m (medium)")
    print("  Epochs: 100")
    print("  Image size: 640")
    print("  Batch size: 8")
    print("  Patience: 20 (early stopping)")
    print("  Device: CPU")
    
    try:
        # Load YOLOv8m model
        print("\nLoading base YOLOv8m model...")
        model = YOLO('yolov8m.pt')
        
        # Train
        print("Training started (this may take 1-2 hours on CPU)...\n")
        results = model.train(
            data=str(data_yaml),
            epochs=100,
            imgsz=640,
            batch=8,
            patience=20,
            device='cpu',  # Use CPU
            verbose=True,
            save=True,
            project='runs/detect',
            name='train4'
        )
        
        print("\n" + "=" * 70)
        print("TRAINING COMPLETE")
        print("=" * 70)
        print(f"\nResults saved to: runs/detect/train4/")
        print(f"Best model: runs/detect/train4/weights/best.pt")
        
        # Print final metrics
        if hasattr(results, 'results_dict'):
            metrics = results.results_dict
            print(f"\nFinal Metrics:")
            print(f"  mAP50: {metrics.get('metrics/mAP50(B)', 'N/A')}")
            print(f"  mAP50-95: {metrics.get('metrics/mAP50-95(B)', 'N/A')}")
        
        print("\n" + "=" * 70)
        print("NEXT STEPS")
        print("=" * 70)
        print("""
1. Update the app with the new model:
   - Edit police_tracker.py (line ~783)
   - Change model path from:
     model_path = 'runs/detect/train3/weights/best.pt'
   - To:
     model_path = 'runs/detect/train4/weights/best.pt'
   
2. Restart the app:
   python police_tracker.py
   
3. Select 'police' model from dropdown to test

4. Compare with previous model - should see improvements!
   - More specific police car detection
   - Fewer false positives on other vehicles
   - Better accuracy on police-specific features
""")
        print("=" * 70)
        
        return True
        
    except Exception as e:
        print(f"\nError during training: {e}")
        import traceback
        traceback.print_exc()
        return False

if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)
